# Generated by Django 2.1 on 2018-08-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('original_link', models.URLField()),
                ('short_link', models.CharField(max_length=10)),
                ('transitions', models.IntegerField(default=0)),
            ],
        ),
    ]
