# Generated by Django 2.1 on 2018-08-24 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20180823_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_pass', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='link',
            name='user',
            field=models.ForeignKey(default='23', on_delete=django.db.models.deletion.CASCADE, to='shortener.User'),
        ),
    ]
