# Generated by Django 2.1 on 2018-08-24 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_auto_20180824_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
