# Generated by Django 2.1 on 2018-08-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0006_link_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='user',
            field=models.IntegerField(default=0),
        ),
    ]
