# Generated by Django 2.1 on 2018-08-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0007_auto_20180824_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='short_tag',
            field=models.CharField(default='', max_length=6),
        ),
    ]
